version: '3.8'
services:
  web:
    depends_on:
      - server
    build: ./front_end
    container_name: laptop_shop_front_end
    develop:
      watch: 
        - path: ./front_end/package*.json
          action: rebuild
        - path: ./front_end
          target: ./usr/src/app
          action: sync

  server:
    depends_on:
      - postgres
    build: ./back_end
    container_name: laptop_shop_back_end
    ports: 
       - 3000:3000
    develop:
      watch:
        - path: ./back_end
          target: ./usr/src/app
          action: sync
        - path: ./back_end/go.mod
          action: rebuild
        - path: ./back_end/go.sum
          action: rebuild

  postgres:
    image: postgres:latest
    restart: always
    container_name: laptop_shop_db
    volumes:
     - laptop_shop:/var/lib/postgresql/data
    ports:
      - 4000:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: laptop_shop

  pgadmin: 
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 5050:5050
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: jrpogiyanyow@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      SECURE_PROXY_SSL_HEADER : None
      SESSION_COOKIE_SECURE : False
      CSRF_COOKIE_SECURE : False
      SERVER_MODE : False



volumes:
  laptop_shop:
     name: laptop_shop
     driver: local
